### **Цель:** собрать модели ниже, и проверить их эффективность в ансамбле.

![diagram](./attach/issc-diagram-1.svg)

In [9]:
from pathlib import Path
import pandas as pd
import collections
from sklearn.preprocessing import MultiLabelBinarizer, StandardScaler
import torch
from random import seed
from sklearn.model_selection import train_test_split, KFold

from importer import *

In [10]:
PATH_ACTIVITY = Path('../DATA/activity/')
PATH_METAINFO = Path('../DATA/metainfo/name+type+ghedonic+gender.csv')
PATH_SPECTRAL = Path('../DATA/spectral/')

### 1. Конвертируем данные EEG-Cutter в нужный формат

In [11]:
activity_df_columns = []

for i in range(2): # На каждое предъявление у нас 3 файла,
                   # 3-й мы будем вычитать из 1-го и из 2-го
    for zn in ZONE_NAMES:
        activity_df_columns.append(f'{zn}_{i+1}')

activity_df = pd.DataFrame(columns=activity_df_columns)

subjects = Path.iterdir(PATH_ACTIVITY)
iii = 0

for subject in sorted(subjects):
    if subject.is_dir():
        files = sorted(filter(lambda f: str(f).endswith('.csv'), Path.iterdir(subject)))
        print(subject, len(files))
        
        for i in range(0, len(files), 3):
            p0 = convert_eegc_activity(files[i])
            p10 = convert_eegc_activity(files[i+1])
            p100 = convert_eegc_activity(files[i+2])

            delta1 = {k: p0[k] - p100[k] for k in p0}
            delta2 = {k: p10[k] - p100[k] for k in p10}

            for k, v in delta1.items():
                activity_df.at[iii, f'{k}_1'] = v
            for k, v in delta2.items():
                activity_df.at[iii, f'{k}_2'] = v

            iii += 1

activity_df

../DATA/activity/Bmet_001 72
../DATA/activity/Bmet_007 18
../DATA/activity/Bmet_011 21
../DATA/activity/Met_003 36
../DATA/activity/Met_004 36
../DATA/activity/Met_005 36
../DATA/activity/Met_006 36
../DATA/activity/Met_009 18
../DATA/activity/Met_010 30
../DATA/activity/Met_011 21
../DATA/activity/Met_013 18
../DATA/activity/NOTUSEDBYSHI 0

,LF_1,MF_1,RF_1,LT_1,MC_1,RT_1,LP_1,MP_1,RP_1,LF_2,MF_2,RF_2,LT_2,MC_2,RT_2,LP_2,MP_2,RP_2
0,0.407766,0.004426,-0.003005,0.082742,-0.07042,-0.024272,0.11594,0.01524,0.083118,-0.249729,0.010985,-0.152518,-0.096465,-0.050107,-0.092899,0.10161,0.143787,-0.057852
1,0.127947,0.108755,0.017622,0.010425,0.043905,0.170563,-0.068743,-0.199585,-0.058262,0.23326,-0.124707,0.045846,0.021066,0.041013,-0.086686,-0.10246,0.014511,0.082752
2,0.035437,-0.068243,0.121052,0.02179,0.054783,-0.120041,0.044528,-0.273911,0.125953,-0.106089,-0.336216,-0.071849,-0.064039,0.169695,0.049142,-0.024852,-0.065088,-0.02176
3,0.420544,-0.395108,0.124535,0.073632,-0.030876,0.045107,-0.072702,-0.419326,0.039387,0.521661,-0.256036,0.395502,0.030065,-0.058379,0.066512,0.044916,-0.165503,-0.012589
4,0.426035,-0.090777,0.196875,0.113779,-0.132729,0.049885,0.011725,-0.156083,-0.007535,-0.388224,-0.058263,-0.124829,-0.165576,0.097775,-0.071409,-0.059249,-0.038213,-0.064399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,0.088191,0.010942,0.022813,0.023624,0.032087,0.15901,0.145301,0.112881,0.317546,-0.104223,-0.009773,0.366493,0.131785,0.043586,-0.309942,0.271386,-0.025747,-0.089629
110,-0.480998,-0.308856,0.290684,0.332032,-0.028832,-0.230101,-0.058325,-0.033538,-0.10915,0.092222,-0.226209,0.168962,0.382058,-0.041152,0.652146,-0.138042,0.120163,-0.142922
111,-0.123498,-0.056899,0.172386,0.194827,0.053798,-0.449821,0.05717,-0.066195,0.025463,-0.073922,0.015785,0.103151,0.270246,-0.026154,-0.038716,0.10544,0.099473,0.460406
112,-0.220663,0.121912,-0.261202,0.107631,0.18335,-0.241005,0.609047,0.042978,-0.902252,-0.578094,0.006552,0.192032,0.483955,-0.031218,0.101183,0.237179,-0.043493,-0.020428
113,-0.191649,-0.008217,0.303108,0.137223,-0.107072,-0.316452,0.019489,0.026943,0.37402,-0.073661,-0.144066,0.069962,0.075874,-0.231667,-0.31994,-0.562633,0.228079,0.759048

### 2. Подготавливаем метаданные и спектральные характеристики

Метаданные (в т.ч. категории запахов), в сочетании с активностями областей по sLORETA, используются в первом датасете, а спектральные характреистики (опять таки в сочетании с метаданными) нужны для второго.

In [12]:
metainfo = pd.read_csv(PATH_METAINFO)

metainfo

,subject,trial,scent_name,scent_type,ghedonic,gender
0,Bmet_001,1,Ладан,Древесные,1,1
1,Bmet_001,2,Розмарин,Хвойные,-1,1
2,Bmet_001,3,Чайное дерево,Хвойные,1,1
3,Bmet_001,4,Нероли,Цветочные,-1,1
4,Bmet_001,5,Майоран,Травянистые / Гурманские,-2,1
...,...,...,...,...,...,...
109,Met_013,2,Сладкий апельсин,Цитрусовые,1,1
110,Met_013,3,Герань,Цветочные,0,1
111,Met_013,4,Бергамот,Цитрусовые,2,1
112,Met_013,5,Лаванда,Цветочные,1,1
113,Met_013,6,Эвкалипт,Хвойные,-1,1

In [13]:
counts = collections.Counter()

for t, c in metainfo['scent_type'].value_counts().items():
    ts = str(t).split('/')
    
    for s in ts:
        ss = s.strip()
        counts[ss] += c

type_c = pd.Series(counts)

type_c.sort_values()

Землистые       2
Мятные          7
Гурманские     15
Травянистые    15
Древесные      17
Хвойные        20
Цветочные      23
Цитрусовые     29
dtype: int64

In [14]:
metainfo['scent_type_split'] = metainfo['scent_type'].apply(
    lambda ts: [t.strip() for t in ts.split('/')]
)

mlb = MultiLabelBinarizer()
groups = mlb.fit_transform(metainfo['scent_type_split'])
groups_df = pd.DataFrame(groups, columns=mlb.classes_)

groups_df

,Гурманские,Древесные,Землистые,Мятные,Травянистые,Хвойные,Цветочные,Цитрусовые
0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,1,0,0
2,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,1,0
4,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...
109,0,0,0,0,0,0,0,1
110,0,0,0,0,0,0,1,0
111,0,0,0,0,0,0,0,1
112,0,0,0,0,0,0,1,0
113,0,0,0,0,0,1,0,0

In [15]:
spectral_df_columns = []

for rhythm in ('δ', 'θ', 'α', 'β', 'γ'):
    # Да, именно в таком порядке!
    # См. https://ru.wikipedia.org/wiki/Ритмы_головного_мозга
    for zn in ZONE_NAMES:
        spectral_df_columns.append(f'{rhythm}_{zn}')

spectral_df = pd.DataFrame(columns=spectral_df_columns).astype('float32')

subjects = Path.iterdir(PATH_SPECTRAL)

for i, r in enumerate(('delta', 'theta', 'alpha', 'beta', 'gamma')):
    spectre = pd.read_csv(PATH_SPECTRAL / (r + '.csv'))

    spectral_df.iloc[:, i*9 : i*9+9] = spectre.iloc[:, 2:11].values

spectral_df

/tmp/ipykernel_523199/4124933630.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.05267017e+03 1.02860034e+03 6.19647461e+02 1.66636145e+03
 1.11820471e+03 5.34555359e+02 8.12467163e+02 7.66041687e+02
 1.63260620e+03 1.00733319e+03 2.06729443e+03 8.19500854e+02
 2.38282090e+04 1.66173344e+05 1.93805188e+05 1.09007086e+05
 3.09718125e+05 2.28121531e+05 1.97585516e+05 3.01948875e+05
 6.60149438e+05 1.03637556e+06 1.00429883e+05 2.37805938e+04
 7.68161774e+01 8.00840530e+01 5.30507355e+01 7.72419052e+01
 5.39906349e+01 6.45988312e+01 3.42844696e+01 2.61776524e+01
 2.78865910e+01 2.71302700e+01 3.28275757e+01 2.98802700e+01
 3.37602043e+01 1.09623756e+02 5.55230751e+01 1.26869408e+02
 8.25429077e+01 7.11396256e+01 6.25417328e+01 9.22183533e+01
 7.25955582e+01 1.18197975e+02 9.15843658e+01 5.77279739e+01
 4.21325500e+02 2.81964050e+02 1.37455612e+02 1.90302155e+02
 1.30559708e+02 9.46272888e+01 2.66327229e+01 2.88456326e+01
 3.72260208e+01 4.43897553e+01 3.80746727e+01 3.27726097e+01
 2.40977898e+01 4.16834869e+02 5.64895592e+01 8.92438431e+01
 8.20334320e+01 9.94840012e+01 2.03092213e+01 4.92268295e+01
 5.28119736e+01 9.38827591e+01 4.33644676e+01 6.91654663e+01
 3.89197540e+01 2.29192638e+01 4.00366402e+01 3.46223259e+01
 5.06958580e+01 3.83095284e+01 1.30901138e+02 4.99248962e+01
 4.29940796e+01 5.25599403e+01 5.04040947e+01 1.15280693e+02
 5.20977554e+01 4.03183075e+02 4.36655083e+01 7.06945419e+01
 6.61138687e+01 7.96800537e+01 5.43040848e+01 1.47518692e+02
 2.70305176e+02 1.30733353e+02 9.16369934e+01 3.23361877e+02
 1.71085632e+02 2.54712982e+02 2.89818085e+02 2.34506546e+02
 1.91904572e+02 8.51886444e+01 9.50908127e+01 9.75459137e+01
 7.86720123e+01 3.90049095e+01 1.02545334e+02 1.37141068e+02
 4.56961784e+01 3.20030289e+01 3.75974274e+01 3.41861839e+01
 3.29695244e+01 3.12996235e+01]' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  spectral_df.iloc[:, i*9 : i*9+9] = spectre.iloc[:, 2:11].values
/tmp/ipykernel_523199/4124933630.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.40846619e+02 3.23704681e+02 2.14890778e+02 5.84639832e+02
 3.21446777e+02 2.62133575e+02 2.27370575e+02 2.41003647e+02
 4.86831879e+02 2.93446442e+02 3.74050598e+02 2.83612946e+02
 1.71389417e+03 6.65896582e+03 7.27368848e+03 5.38296875e+03
 1.02803770e+04 8.56676953e+03 6.53066309e+03 7.90983545e+03
 2.03588047e+04 2.73740195e+04 2.88916089e+03 2.56957031e+03
 1.26197075e+02 1.30764038e+02 8.21058350e+01 1.33064804e+02
 9.51573181e+01 9.97972946e+01 5.60541916e+01 5.05638619e+01
 4.57462578e+01 3.97027893e+01 4.51048241e+01 4.56910172e+01
 5.53846169e+01 1.13381279e+02 7.28841782e+01 1.14317184e+02
 9.36389542e+01 8.47758484e+01 8.71426086e+01 2.15627930e+02
 9.11743469e+01 1.14238037e+02 1.07316673e+02 8.22327728e+01
 1.59410187e+02 2.02611969e+02 1.39177261e+02 1.70413193e+02
 1.06967606e+02 9.37630005e+01 4.31532936e+01 5.98753815e+01
 6.08099861e+01 3.97478867e+01 6.96468582e+01 5.20963516e+01
 3.85852585e+01 1.58910721e+02 3.04173679e+01 4.14272995e+01
 4.37353897e+01 7.97572784e+01 1.86060390e+01 3.06892834e+01
 3.93920670e+01 5.92854347e+01 3.31123276e+01 3.27451324e+01
 1.79743271e+01 4.58225060e+01 5.24944992e+01 5.53417206e+01
 8.38440399e+01 6.21932106e+01 1.67204086e+02 6.85433273e+01
 6.16621628e+01 7.25381241e+01 7.54477921e+01 1.56894211e+02
 7.79418335e+01 6.87511719e+02 7.13776627e+01 1.42386368e+02
 1.14020149e+02 1.00029297e+02 9.05534058e+01 2.18483139e+02
 3.25004028e+02 2.17867783e+02 1.37333527e+02 3.97598846e+02
 2.16802887e+02 3.91938354e+02 3.26583801e+02 3.41304443e+02
 3.16800171e+02 1.53496643e+02 1.23238091e+02 1.56673492e+02
 1.68053970e+02 7.31565018e+01 1.54763519e+02 2.64535309e+02
 8.38804855e+01 5.75646400e+01 6.41937180e+01 4.87190933e+01
 8.82547913e+01 8.57705231e+01]' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  spectral_df.iloc[:, i*9 : i*9+9] = spectre.iloc[:, 2:11].values
/tmp/ipykernel_523199/4124933630.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.17891632e+02 5.23671509e+02 3.62819153e+02 9.65549133e+02
 6.84041443e+02 4.34460907e+02 7.16730530e+02 4.32870087e+02
 1.07298206e+03 6.44064026e+02 1.33231018e+03 6.06054565e+02
 9.97833594e+04 5.31437500e+05 4.33401188e+05 1.32868266e+05
 6.47204500e+05 1.19486820e+05 2.42799562e+05 7.72644375e+05
 2.71423375e+05 9.33525062e+05 3.20258938e+05 2.53301650e+06
 1.98992615e+02 9.27170639e+01 9.85293579e+01 1.49779587e+02
 7.64855423e+01 1.04328110e+02 4.49522514e+01 3.50253105e+01
 3.49428177e+01 2.80470943e+01 3.96969185e+01 3.98136711e+01
 4.33857269e+01 1.40783783e+02 8.70183182e+01 1.19634514e+02
 1.06736153e+02 1.07174362e+02 1.15737198e+02 2.02956741e+02
 1.01254112e+02 1.52155533e+02 1.27082024e+02 9.87341309e+01
 2.02307449e+02 2.91831818e+02 2.44711807e+02 3.12224365e+02
 1.32466766e+02 1.43827011e+02 3.98450966e+01 6.25196152e+01
 4.18836517e+01 3.96722717e+01 6.66198120e+01 4.10352211e+01
 3.71355171e+01 4.84631287e+02 2.14844055e+01 6.51955337e+01
 2.15262360e+02 4.70939407e+01 1.99005108e+01 2.69935646e+01
 4.47377090e+01 1.03278847e+02 6.64814682e+01 2.84380703e+01
 3.99161453e+01 4.92172165e+01 5.33387108e+01 5.74454384e+01
 6.75049896e+01 5.05548134e+01 2.44327911e+02 6.75022964e+01
 6.85597000e+01 9.96643982e+01 8.15614471e+01 2.03830032e+02
 7.92688751e+01 4.77974121e+02 4.62126274e+01 1.53843796e+02
 1.01330986e+02 8.00848923e+01 1.11419418e+02 2.02709473e+02
 4.35613617e+02 2.52958176e+02 2.26587723e+02 6.00754456e+02
 3.06678162e+02 3.96741760e+02 4.37288818e+02 3.02332397e+02
 2.68750244e+02 3.37831207e+02 9.05300598e+01 1.19845108e+02
 1.77167343e+02 6.68777618e+01 1.50521545e+02 3.83920654e+02
 9.91691284e+01 7.97922592e+01 7.75072479e+01 5.20383263e+01
 6.13869934e+01 7.26137161e+01]' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  spectral_df.iloc[:, i*9 : i*9+9] = spectre.iloc[:, 2:11].values
/tmp/ipykernel_523199/4124933630.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[6.24345215e+02 3.08832690e+03 2.06366284e+03 5.26085498e+03
 4.35261133e+03 3.60216309e+02 2.12543604e+03 6.11999023e+02
 3.65692969e+03 5.75635132e+02 5.36901562e+03 1.01891101e+03
 3.71553242e+04 2.16835438e+05 1.77517469e+05 6.22299453e+04
 2.94909219e+05 5.23460000e+04 1.18417383e+05 4.01614281e+05
 1.34871016e+05 5.06682281e+05 1.91012156e+05 1.24838562e+06
 5.27620430e+01 5.35457268e+01 4.00772438e+01 7.03272171e+01
 4.04946136e+01 7.10390244e+01 2.26962147e+01 1.99286861e+01
 2.36687756e+01 1.75140266e+01 2.51499214e+01 1.77068253e+01
 3.62828178e+01 8.86598740e+01 4.95805588e+01 8.19757690e+01
 6.43775177e+01 5.31795692e+01 5.68011322e+01 6.97747040e+01
 7.09079437e+01 1.09518562e+02 6.27523537e+01 5.47605324e+01
 1.13232857e+02 1.77757919e+02 1.10602966e+02 1.09328712e+02
 7.63151779e+01 8.22675323e+01 3.08401165e+01 3.47837105e+01
 5.30147018e+01 4.19392013e+01 3.57229500e+01 3.39910584e+01
 2.46237392e+01 1.40847580e+02 2.60673714e+01 3.79269600e+01
 2.79172020e+01 3.17805710e+01 3.73493538e+01 3.58320160e+01
 3.59510765e+01 4.58325615e+01 3.50694122e+01 3.99952202e+01
 3.63017464e+01 3.20189743e+01 3.49272385e+01 2.90721798e+01
 4.26411781e+01 3.39827499e+01 8.08977661e+01 3.05357456e+01
 3.40022888e+01 5.58237762e+01 5.34648705e+01 6.14157028e+01
 4.98093872e+01 5.99465942e+02 5.36930580e+01 7.76314087e+01
 6.67283554e+01 7.55080490e+01 5.38505058e+01 1.20193214e+02
 2.37299362e+02 1.07807961e+02 7.32009354e+01 1.93025620e+02
 1.05858742e+02 2.41139404e+02 1.98719788e+02 3.17528625e+02
 1.13809181e+02 4.16780167e+01 6.15454521e+01 9.54374847e+01
 9.91035309e+01 3.09704876e+01 8.12832870e+01 1.87268890e+02
 4.02737999e+01 2.63613358e+01 3.21335373e+01 2.20926437e+01
 2.89868832e+01 3.32432327e+01]' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  spectral_df.iloc[:, i*9 : i*9+9] = spectre.iloc[:, 2:11].values
/tmp/ipykernel_523199/4124933630.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 356.83587646  236.54852295  282.01766968  560.36657715  409.99954224
  269.27566528  345.67523193  283.64590454  625.09069824  378.86456299
  459.14468384  299.09725952  633.45202637 1026.69311523  845.09283447
  636.59509277 1097.79760742  898.85705566  591.15789795  979.42138672
 1133.22375488 1621.63110352  506.64019775 2640.1159668   115.9048233
  105.0085526    88.97680664  160.4229889    96.54907227  115.499649
   45.16020966   46.6641922    37.73248672   40.46595383   63.42809296
   35.52070618   45.49266815  102.2720337    60.98936081  102.1133347
   81.50757599   64.39716339   77.75973511  192.4680786    92.79833221
  151.4064331    83.43086243   69.34842682  274.5270691   533.4090576
  213.9600983   228.4799194   160.783493    156.8167572    61.69804001
   65.05590057   55.44192123   72.0303421    99.37232208   65.22132874
   48.54655075  110.3480835    21.35549736   29.16172218   23.95533371
   34.34139633   13.3717165    31.26821518   27.34253311   78.0699234
   27.37869263   26.49035645   20.18435478   41.58559418   52.52293015
   44.13754654   50.8404007    50.70828247  126.93074799   53.35395432
   42.13047791   66.3972702    78.06276703  113.00206757   65.96239471
  644.81555176   56.510849    101.23188782  175.10493469   90.1139679
   59.67472076  132.38346863  238.60369873  188.37748718  188.13194275
  402.1758728   147.34417725  666.69525146  166.08602905 1874.30993652
  718.83026123   57.11548233   83.84705353  129.21713257  123.72522736
   52.5681076   105.22367859  170.28186035  188.31066895  282.84188843
  119.77005768   51.08350754   49.4189415    86.21405029]' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  spectral_df.iloc[:, i*9 : i*9+9] = spectre.iloc[:, 2:11].values
/tmp/ipykernel_523199/4124933630.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[8.47289734e+02 3.41256152e+03 2.57175146e+03 7.79012500e+03
 4.62206299e+03 9.66596741e+02 2.93492114e+03 1.10455701e+03
 1.05995039e+04 3.13079419e+03 1.75066211e+04 1.15951331e+03
 1.66523288e+06 9.08054500e+06 7.30226800e+06 2.00008088e+06
 1.09489410e+07 1.73984062e+06 4.05875225e+06 1.36281290e+07
 3.93349175e+06 1.54659450e+07 5.84556900e+06 4.85417040e+07
 9.83277206e+01 7.70457153e+01 6.67131882e+01 1.07732697e+02
 8.26902771e+01 8.46784973e+01 3.87352409e+01 3.92402534e+01
 3.97922783e+01 3.10550728e+01 3.53794098e+01 4.06183434e+01
 4.70465202e+01 9.97323074e+01 4.78295326e+01 9.25512390e+01
 7.49498672e+01 6.68060226e+01 7.41419907e+01 9.36746368e+01
 7.88275452e+01 6.64855728e+01 7.99588089e+01 6.93750381e+01
 1.28860275e+02 6.92952881e+01 6.76115951e+01 6.87478714e+01
 4.23494263e+01 4.95800247e+01 2.76882648e+01 4.91336937e+01
 4.23356094e+01 2.47979698e+01 4.62882156e+01 3.52924309e+01
 3.84462471e+01 1.84543778e+02 2.56229858e+01 4.22009277e+01
 6.46245804e+01 2.75198536e+01 2.52212906e+01 6.53858566e+01
 3.24803352e+01 4.65189095e+01 4.41342850e+01 2.96686974e+01
 3.77995453e+01 8.28160324e+01 7.34751129e+01 7.33041840e+01
 9.21918335e+01 7.52156906e+01 3.26488312e+02 6.92978973e+01
 6.18113899e+01 8.13213730e+01 1.07897453e+02 1.71967300e+02
 1.05513916e+02 2.92091827e+02 5.57980309e+01 8.06832733e+01
 6.58234940e+01 4.99549294e+01 6.35658569e+01 1.47089981e+02
 4.17303467e+02 2.17620834e+02 9.93650894e+01 2.31613281e+02
 1.59936264e+02 3.64170349e+02 2.84266998e+02 2.04896515e+02
 2.16359344e+02 5.03832550e+02 4.30952148e+02 5.20735535e+02
 2.86819727e+03 6.23083740e+02 7.83584778e+02 9.87679883e+03
 3.76611824e+01 2.75929031e+01 3.62733345e+01 2.42702885e+01
 3.58569183e+01 3.23150520e+01]' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  spectral_df.iloc[:, i*9 : i*9+9] = spectre.iloc[:, 2:11].values
/tmp/ipykernel_523199/4124933630.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[5.44589966e+02 2.57162598e+03 2.15557349e+03 5.37261572e+03
 3.48054858e+03 8.85600891e+02 2.09793848e+03 6.46786865e+02
 4.40537451e+03 1.02005316e+03 6.68067285e+03 1.06235706e+03
 9.53720781e+04 4.79114531e+05 3.93659250e+05 1.20295891e+05
 5.54373375e+05 1.10458055e+05 2.05259781e+05 6.29379438e+05
 2.27970453e+05 7.41286125e+05 2.47935531e+05 2.25688800e+06
 5.82846527e+01 5.67662048e+01 4.22654495e+01 7.05307007e+01
 4.44930420e+01 4.86662293e+01 1.81037826e+01 1.64164715e+01
 1.82599716e+01 1.64138069e+01 2.18788185e+01 2.33833313e+01
 2.31209717e+01 5.60818405e+01 3.60028152e+01 6.73625412e+01
 4.50411720e+01 3.82306900e+01 4.00549278e+01 6.10235748e+01
 6.49490280e+01 6.44762955e+01 5.69573669e+01 3.45566292e+01
 7.34958801e+01 1.11262649e+02 5.95634880e+01 1.24022171e+02
 5.15405350e+01 4.77641907e+01 2.37096863e+01 2.56269703e+01
 3.92641754e+01 2.58621216e+01 4.20300980e+01 2.61391602e+01
 3.76063805e+01 2.09394135e+02 4.73305588e+01 6.15258675e+01
 5.44207687e+01 3.71761856e+01 3.76952782e+01 7.27971039e+01
 5.97236633e+01 6.62154617e+01 5.68760414e+01 4.81278534e+01
 5.63909912e+01 4.11871185e+01 4.56738968e+01 3.15831051e+01
 4.68881340e+01 4.95842896e+01 1.51279404e+02 3.52110596e+01
 4.29291458e+01 5.73461952e+01 8.12565231e+01 7.59739685e+01
 4.68170357e+01 2.17752075e+02 3.20649986e+01 3.68204842e+01
 3.46953201e+01 4.71372108e+01 3.87278366e+01 7.51180267e+01
 2.18115646e+02 7.97812271e+01 5.68302116e+01 1.31028503e+02
 9.06037827e+01 1.62889023e+02 1.04137085e+02 2.00419327e+02
 1.07819885e+02 7.11913605e+01 7.69772186e+01 1.07067703e+02
 2.56920410e+02 8.23983383e+01 1.13502884e+02 5.95699280e+02
 2.86220798e+01 2.14678116e+01 2.17408886e+01 1.71925564e+01
 2.88288002e+01 2.45302944e+01]' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  spectral_df.iloc[:, i*9 : i*9+9] = spectre.iloc[:, 2:11].values
/tmp/ipykernel_523199/4124933630.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[8.17558960e+02 4.52535693e+03 2.89443701e+03 8.16858301e+03
 6.39453076e+03 8.83423218e+02 3.49073291e+03 8.63895508e+02
 5.56611475e+03 1.07636255e+03 8.02091650e+03 1.62464465e+03
 1.07365508e+04 4.16016484e+04 3.99254883e+04 1.69999668e+04
 4.41746133e+04 2.23506660e+04 2.24861484e+04 4.37269805e+04
 3.31068633e+04 5.64765195e+04 2.23028613e+04 1.51333812e+05
 1.15560562e+02 1.64651733e+02 1.10711334e+02 1.47911911e+02
 1.35574020e+02 1.13214249e+02 4.81687698e+01 5.52176285e+01
 4.41601028e+01 4.28544540e+01 5.66209259e+01 6.23266182e+01
 6.14428597e+01 9.75461578e+01 7.10688477e+01 9.47110901e+01
 1.16434845e+02 7.28993988e+01 8.94504852e+01 1.20634499e+02
 1.09579895e+02 1.56042786e+02 1.09793205e+02 7.36490402e+01
 1.45040695e+02 2.58214081e+02 1.47559677e+02 1.90131531e+02
 9.78636246e+01 1.09837685e+02 5.70978203e+01 6.84194336e+01
 9.19605560e+01 5.36472397e+01 9.39179840e+01 5.68632698e+01
 6.29177246e+01 1.89857330e+02 5.10543861e+01 6.47156296e+01
 3.91799774e+01 2.60214138e+01 3.28184013e+01 4.23357925e+01
 9.39262009e+01 5.23876762e+01 7.76823349e+01 6.67307587e+01
 3.73336029e+01 7.33869858e+01 8.68742752e+01 7.63530273e+01
 1.08601173e+02 9.13385315e+01 2.22564331e+02 8.64504013e+01
 8.65816422e+01 1.13715599e+02 1.39874298e+02 1.77867645e+02
 1.26148598e+02 7.13381714e+02 1.12009628e+02 1.18525810e+02
 1.10456177e+02 1.89393188e+02 8.61076889e+01 1.80955032e+02
 4.92770386e+02 1.61516922e+02 1.36490768e+02 3.16093597e+02
 1.48640579e+02 3.49802460e+02 2.58184113e+02 4.55672638e+02
 3.56597534e+02 7.94828033e+01 9.35873795e+01 2.42182404e+02
 8.72168121e+01 6.99042740e+01 1.41855087e+02 3.56354340e+02
 7.36727905e+01 7.57607727e+01 5.87522278e+01 4.85126457e+01
 5.69032135e+01 8.29989243e+01]' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  spectral_df.iloc[:, i*9 : i*9+9] = spectre.iloc[:, 2:11].values
/tmp/ipykernel_523199/4124933630.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[5.90748215e+01 8.02036972e+01 5.14221153e+01 1.49589188e+02
 1.51863632e+02 5.67758636e+01 8.94137650e+01 5.28795738e+01
 2.71017029e+02 6.26322021e+01 2.94868500e+02 9.54009933e+01
 1.59866230e+04 6.25280820e+04 5.04944492e+04 2.92186797e+04
 7.99610703e+04 4.67066094e+04 1.65627539e+04 5.62817041e+03
 1.32237594e+05 2.03060875e+05 3.15416914e+04 3.51327148e+04
 9.67222748e+01 9.97581558e+01 9.27866440e+01 1.53896713e+02
 5.86354141e+01 9.36794052e+01 2.65457821e+01 3.12493820e+01
 2.73837147e+01 2.55624409e+01 2.71084652e+01 3.26315079e+01
 2.31226768e+01 7.04957199e+01 7.41627808e+01 7.92804031e+01
 9.90008621e+01 9.79592056e+01 9.21948929e+01 1.06689598e+02
 1.14934776e+02 9.37372971e+01 9.86962585e+01 1.06739571e+02
 8.96225433e+01 2.44229240e+01 1.96740532e+01 2.75563698e+01
 1.62090073e+01 1.59915733e+01 1.39442101e+01 2.00978584e+01
 1.68050194e+01 1.68464851e+01 1.70858841e+01 1.71072254e+01
 1.61083965e+01 1.01454000e+01 5.89941788e+00 7.05050659e+00
 8.71252728e+00 8.03691673e+00 7.31259871e+00 7.17338943e+00
 6.64062023e+00 9.09021568e+00 7.68561697e+00 7.77859640e+00
 7.36087942e+00 2.47142944e+01 2.27271233e+01 2.35713139e+01
 3.33841591e+01 2.53591557e+01 3.47021790e+01 2.75581436e+01
 2.99060345e+01 2.72949772e+01 2.39507618e+01 4.16068611e+01
 2.31230392e+01 2.97889313e+02 3.49801292e+01 4.40304909e+01
 5.26237793e+01 5.78086510e+01 3.75203133e+01 1.88525101e+02
 7.16713501e+02 2.86328430e+02 2.53051071e+02 4.51758423e+02
 3.53173248e+02 5.20006348e+02 4.25921600e+02 3.83634979e+02
 4.84725311e+02 6.84267807e+01 3.47612114e+01 6.09358521e+01
 4.28212166e+01 3.95704269e+01 6.11434479e+01 9.89506378e+01
 2.98730831e+01 2.11671772e+01 2.59022102e+01 2.12840576e+01
 2.08618736e+01 2.33590870e+01]' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  spectral_df.iloc[:, i*9 : i*9+9] = spectre.iloc[:, 2:11].values
/tmp/ipykernel_523199/4124933630.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.11935219e+02 1.22795891e+02 8.84096985e+01 1.75561676e+02
 1.26390121e+02 8.46271667e+01 1.11678101e+02 7.55148468e+01
 1.92201385e+02 9.12589340e+01 1.96556244e+02 1.32947052e+02
 3.52868530e+03 1.56136396e+04 1.39484463e+04 7.90129883e+03
 2.34413086e+04 1.60572832e+04 4.78097705e+03 1.80087280e+03
 4.71735898e+04 7.09453750e+04 9.77498145e+03 2.36903149e+03
 6.11284370e+01 6.89934387e+01 5.66813202e+01 8.58601685e+01
 3.91995888e+01 5.72851791e+01 1.75789738e+01 1.80144539e+01
 1.97354736e+01 1.72690029e+01 1.74068031e+01 1.59627647e+01
 1.84840641e+01 4.27850800e+01 4.95355721e+01 5.43693542e+01
 6.34790077e+01 6.31968536e+01 5.28558960e+01 6.84700546e+01
 6.82872162e+01 5.55288811e+01 5.72735863e+01 6.53468933e+01
 6.91373520e+01 2.19328842e+01 1.74245567e+01 2.16864262e+01
 1.25395613e+01 1.21082296e+01 8.83521938e+00 1.06822329e+01
 9.90643120e+00 1.06808701e+01 1.10847111e+01 9.50445557e+00
 9.06826782e+00 1.12080383e+01 6.79124880e+00 7.32702589e+00
 1.06119442e+01 8.42183113e+00 7.29098606e+00 9.43022442e+00
 7.61661625e+00 1.12238932e+01 7.78125381e+00 8.86963654e+00
 7.80552816e+00 1.58406754e+01 1.82411270e+01 1.72416000e+01
 2.58337364e+01 1.89986038e+01 2.62892036e+01 1.78368225e+01
 2.24534569e+01 1.95107670e+01 1.52423258e+01 3.14960728e+01
 1.68829937e+01 1.52484314e+02 1.74457703e+01 2.27679539e+01
 2.98114414e+01 2.61756153e+01 1.92154541e+01 9.81748962e+01
 3.14490417e+02 1.44765167e+02 1.28646866e+02 2.36733139e+02

,δ_LF,δ_MF,δ_RF,δ_LT,δ_MC,δ_RT,δ_LP,δ_MP,δ_RP,θ_LF,...,β_RP,γ_LF,γ_MF,γ_RF,γ_LT,γ_MC,γ_RT,γ_LP,γ_MP,γ_RP
0,394.282043,1052.670166,340.846619,417.891632,624.345215,356.835876,847.289734,544.589966,817.558960,59.074821,...,37.029888,199.981049,71.096779,32.656998,64.772011,1200.609009,52.518333,961.223938,958.408447,1641.589722
1,762.995667,1028.600342,323.704681,523.671509,3088.326904,236.548523,3412.561523,2571.625977,4525.356934,80.203697,...,93.544815,220.646896,78.612442,32.818657,75.055435,1240.861206,62.599491,1048.204224,1000.914795,1702.527710
2,624.088623,619.647461,214.890778,362.819153,2063.662842,282.017670,2571.751465,2155.573486,2894.437012,51.422115,...,78.263687,277.299713,98.526665,36.027576,97.729782,1324.911621,68.919403,1248.845947,1095.593994,1826.238159
3,1850.210327,1666.361450,584.639832,965.549133,5260.854980,560.366577,7790.125000,5372.615723,8168.583008,149.589188,...,160.597122,501.910645,176.329025,54.761299,202.971405,2008.698364,63.239769,2481.108643,1757.602661,2808.519043
4,1587.042114,1118.204712,321.446777,684.041443,4352.611328,409.999542,4622.062988,3480.548584,6394.530762,151.863632,...,170.729218,522.595520,182.873444,52.384823,259.869598,1875.250000,72.528259,2702.287109,1709.924683,2638.802734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,52.529495,32.003029,57.564640,79.792259,26.361336,282.841888,27.592903,21.467812,75.760773,21.167177,...,20.194298,19.207043,9.158166,14.601722,30.616104,4.883770,12.496562,6.511979,5.536946,14.388382
110,52.660519,37.597427,64.193718,77.507248,32.133537,119.770058,36.273335,21.740889,58.752228,25.902210,...,20.669523,15.640918,6.016054,11.199177,16.251923,4.368326,16.239906,5.572407,4.487237,13.464450
111,48.808262,34.186184,48.719093,52.038326,22.092644,51.083508,24.270288,17.192556,48.512646,21.284058,...,21.487478,23.787455,9.715988,13.419046,23.677118,5.281605,14.337770,7.586077,5.050881,15.914467
112,53.893646,32.969524,88.254791,61.386993,28.986883,49.418941,35.856918,28.828800,56.903214,20.861874,...,29.863012,28.553324,14.476421,20.893141,66.449112,7.059452,19.008575,9.604828,6.554445,22.771816
113,73.004387,31.299623,85.770523,72.613716,33.243233,86.214050,32.315052,24.530294,82.998924,23.359087,...,24.741615,22.186913,10.574285,16.127481,25.793552,5.740025,13.683353,8.557536,5.921005,12.670334

Последняя проверка, что ничего не поехало по одному месту:

In [16]:
print(
    metainfo.shape[1],    # = 2 + 2 + 1 + 1 + 1
    groups_df.shape[1],   # = От 8 до 10
    activity_df.shape[1], # = CSV_PER_CAT * 9
    spectral_df.shape[1]  # = 5 * 9
)

assert(metainfo.shape[0] == groups_df.shape[0] == activity_df.shape[0] == spectral_df.shape[0])

7 8 18 45

### 3. Агрегируем датасеты для обоих версий модели

**ДАТАСЕТ 1:** пол + encode категории(-й) + средняя активность областей на sLORETA --> гедоническая оценка

**ДАТАСЕТ 2:** пол + encode категории(-й) + спектральные характеристики областей --> гедоническая оценка

In [17]:
dataset_input1 = pd.concat([
    metainfo['gender'],
    groups_df,
    activity_df
], axis=1).astype('float32')

dataset_input2 = pd.concat([
    metainfo['gender'],
    groups_df,
    spectral_df
], axis=1).astype('float32')

dataset_output = pd.concat([
    # metainfo['gender'],
    metainfo['ghedonic'].apply(lambda g: (g + 3.0) / 5.0),
]).astype('float32')

In [18]:
RANDOM_SEED = 80085 # Spoopy!!

torch.manual_seed(RANDOM_SEED)
torch.cuda.manual_seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
seed(RANDOM_SEED)

# print(dataset_input1.iloc[21])

In [19]:
train_input1, test_input1, train_output, test_output = train_test_split(
    dataset_input1, dataset_output, test_size=0.3, random_state=RANDOM_SEED
)

train_input2, test_input2, _, _ = train_test_split(
    dataset_input2, dataset_output, test_size=0.3, random_state=RANDOM_SEED
)

scaler1 = StandardScaler()
train_input1 = scaler1.fit_transform(train_input1)
test_input1 = scaler1.transform(test_input1)
scaler2 = StandardScaler()
train_input2 = scaler2.fit_transform(train_input2)
test_input2 = scaler2.transform(test_input2)

In [20]:
train_input1

array([[-1.661898  , -0.3806935 , -0.4438127 , ...,  0.27947778,
        -0.02593173,  0.15660825],
       [ 0.6017217 , -0.3806935 , -0.4438127 , ...,  0.27797696,
        -0.16836888, -0.8145145 ],
       [-1.661898  , -0.3806935 ,  2.253203  , ...,  0.6923419 ,
         0.66200376,  1.1877035 ],
       ...,
       [-1.661898  , -0.3806935 , -0.4438127 , ..., -1.453573  ,
        -0.240304  , -1.0091723 ],
       [ 0.6017217 , -0.3806935 , -0.4438127 , ...,  1.204727  ,
        -0.06404526, -0.1363709 ],
       [ 0.6017217 ,  2.626785  , -0.4438127 , ...,  0.49357003,
         0.8237692 ,  0.5413129 ]], shape=(79, 27), dtype=float32)

In [21]:
train_input2

array([[-1.661898  , -0.3806935 , -0.4438127 , ..., -0.33282265,
        -0.34024307, -0.39495024],
       [ 0.6017217 , -0.3806935 , -0.4438127 , ..., -0.33281213,
        -0.34007192, -0.391003  ],
       [-1.661898  , -0.3806935 ,  2.253203  , ..., -0.332817  ,
        -0.3401041 , -0.3898273 ],
       ...,
       [-1.661898  , -0.3806935 , -0.4438127 , ..., -0.33282393,
        -0.34025002, -0.39528495],
       [ 0.6017217 , -0.3806935 , -0.4438127 , ..., -0.33282718,
        -0.34027717, -0.39545208],
       [ 0.6017217 ,  2.626785  , -0.4438127 , ..., -0.3328154 ,
        -0.34013903, -0.3919569 ]], shape=(79, 54), dtype=float32)

In [22]:
train_output.astype(np.float32)

79     0.6
95     0.6
43     0.8
49     1.0
5      0.2
      ...
10     0.6
106    0.8
39     0.8
109    0.8
97     1.0
Name: ghedonic, Length: 79, dtype: float32

### 4. Собственно, проверка датасетов на моделях!

Архитектура примерно такая же, как и в прошылй раз, покрмр на текущий момент

In [23]:
def learning_pipeline(
        model,
        train_input,
        train_output,
        test_input,
        test_output,
        comments=True
    ):
    train_input_t = torch.tensor(train_input, dtype=torch.float32)
    train_output_t = torch.tensor(train_output.values, dtype=torch.float32).unsqueeze(1)
    test_input_t = torch.tensor(test_input, dtype=torch.float32)
    test_output_t = torch.tensor(test_output.values, dtype=torch.float32).unsqueeze(1)

    criterion = torch.nn.MSELoss() 
    optimizer = torch.optim.Adam(model.parameters(), lr=0.00002, weight_decay=0.001)


    best_pred = None
    best_loss = 99.99
    best_e = -1

    for e in range(999999999):
        model.train()
        optimizer.zero_grad()
        
        train_pred = model(train_input_t)
        train_loss = criterion(train_pred, train_output_t)
        
        train_loss.backward()
        optimizer.step()

        model.eval()
        with torch.no_grad():
            test_pred = model(test_input_t)
            test_loss = criterion(test_pred, test_output_t)

            if test_loss.item() < best_loss:
                best_e = e
                best_loss = test_loss.item()
                best_pred = test_pred.clone()

        if e % 200 == 0:
            if comments:
                print(f'Потери на train на эпохе {e} = {train_loss.item()}')
                print(f'Потери на test на эпохе {e} = {test_loss.item()}\n')

            if e - best_e >= 2000:
                if comments:
                    print('Модель перестала учиться, this is the end...')

                print(f'Лучшая эпоха: {best_e} (потери на test: {best_loss})')
                break
    
    return (
        test_output_t.squeeze().numpy(),
        best_pred.squeeze().numpy(),
        best_loss
    )

In [24]:
DROPOUT_P = 0.1


class Dataset1Model(torch.nn.Module):
    def __init__(self):
        super(Dataset1Model, self).__init__()

        self.fc1 = torch.nn.Linear(27, 12)     # = Гендер (1) + Категории (8) + Активности областей (9*2)
        self.do1 = torch.nn.Dropout(DROPOUT_P) # Контрим переобучение на малом кол-ве данных
        self.fc2 = torch.nn.Linear(12, 6)      # Расширяем
        self.do2 = torch.nn.Dropout(DROPOUT_P) # Контрим переобучение на малом кол-ве данных
        self.out = torch.nn.Linear(6, 1)       # = Гедоническая оценка (1)

    def forward(self, x):
        x = torch.nn.functional.silu(self.fc1(x))
        x = self.do1(x)
        x = torch.nn.functional.silu(self.fc2(x))
        x = self.do2(x)
        x = self.out(x)

        return x

class Dataset2Model(torch.nn.Module):
    def __init__(self):
        super(Dataset2Model, self).__init__()

        self.fc1 = torch.nn.Linear(54, 16)     # = Гендер (1) + Категории (8) + Спектральные хар-ки (9*5)
        self.do1 = torch.nn.Dropout(DROPOUT_P) # Контрим переобучение на малом кол-ве данных
        self.fc2 = torch.nn.Linear(16, 8)      # Расширяем
        self.do2 = torch.nn.Dropout(DROPOUT_P) # Контрим переобучение на малом кол-ве данных
        self.out = torch.nn.Linear(8, 1)       # = Гедоническая оценка (1)

    def forward(self, x):
        x = torch.nn.functional.silu(self.fc1(x))
        x = self.do1(x)
        x = torch.nn.functional.silu(self.fc2(x))
        x = self.do2(x)
        x = self.out(x)

        return x

In [27]:
learning_pipeline(
    Dataset1Model(),
    train_input1,
    train_output,
    test_input1,
    test_output
)

Потери на train на эпохе 0 = 1.1738606691360474
Потери на test на эпохе 0 = 1.0682622194290161

Потери на train на эпохе 200 = 1.1477755308151245
Потери на test на эпохе 200 = 1.0438202619552612

Потери на train на эпохе 400 = 1.1204524040222168
Потери на test на эпохе 400 = 1.0197935104370117

Потери на train на эпохе 600 = 1.098256230354309
Потери на test на эпохе 600 = 0.9959567189216614

Потери на train на эпохе 800 = 1.076558232307434
Потери на test на эпохе 800 = 0.9723265767097473

Потери на train на эпохе 1000 = 1.042858362197876
Потери на test на эпохе 1000 = 0.9489963054656982

Потери на train на эпохе 1200 = 1.0140366554260254
Потери на test на эпохе 1200 = 0.9259944558143616

Потери на train на эпохе 1400 = 0.9806649088859558
Потери на test на эпохе 1400 = 0.903328001499176

Потери на train на эпохе 1600 = 0.9641796946525574
Потери на test на эпохе 1600 = 0.8812092542648315

Потери на train на эпохе 1800 = 0.9389581084251404
Потери на test на эпохе 1800 = 0.8594788908958435

Потери на train на эпохе 2000 = 0.9004624485969543
Потери на test на эпохе 2000 = 0.8384236693382263

Потери на train на эпохе 2200 = 0.8758963942527771
Потери на test на эпохе 2200 = 0.8182324767112732

Потери на train на эпохе 2400 = 0.8373765349388123
Потери на test на эпохе 2400 = 0.7985734939575195

Потери на train на эпохе 2600 = 0.7881255745887756
Потери на test на эпохе 2600 = 0.7796735763549805

Потери на train на эпохе 2800 = 0.7598784565925598
Потери на test на эпохе 2800 = 0.7617727518081665

Потери на train на эпохе 3000 = 0.7591391205787659
Потери на test на эпохе 3000 = 0.7441728115081787

Потери на train на эпохе 3200 = 0.7125080227851868
Потери на test на эпохе 3200 = 0.7271073460578918

Потери на train на эпохе 3400 = 0.7033736109733582
Потери на test на эпохе 3400 = 0.7106112837791443

Потери на train на эпохе 3600 = 0.6751118898391724
Потери на test на эпохе 3600 = 0.6947610378265381

Потери на train на эпохе 3800 = 0.6251099109649658
Потери на test на эпохе 3800 = 0.6795672178268433

Потери на train на эпохе 4000 = 0.58082115650177
Потери на test на эпохе 4000 = 0.6641271710395813

Потери на train на эпохе 4200 = 0.5526963472366333
Потери на test на эпохе 4200 = 0.6493253707885742

Потери на train на эпохе 4400 = 0.5465783476829529
Потери на test на эпохе 4400 = 0.6342343091964722

Потери на train на эпохе 4600 = 0.5179157853126526
Потери на test на эпохе 4600 = 0.6190018057823181

Потери на train на эпохе 4800 = 0.4901813566684723
Потери на test на эпохе 4800 = 0.6035265922546387

Потери на train на эпохе 5000 = 0.4563688039779663
Потери на test на эпохе 5000 = 0.5872707962989807

Потери на train на эпохе 5200 = 0.40749281644821167
Потери на test на эпохе 5200 = 0.5697692036628723

Потери на train на эпохе 5400 = 0.3837864398956299
Потери на test на эпохе 5400 = 0.5513060688972473

Потери на train на эпохе 5600 = 0.35225409269332886
Потери на test на эпохе 5600 = 0.532029926776886

Потери на train на эпохе 5800 = 0.38152801990509033
Потери на test на эпохе 5800 = 0.5140931606292725

Потери на train на эпохе 6000 = 0.35638928413391113
Потери на test на эпохе 6000 = 0.4969446361064911

Потери на train на эпохе 6200 = 0.27607426047325134
Потери на test на эпохе 6200 = 0.4785447120666504

Потери на train на эпохе 6400 = 0.27129077911376953
Потери на test на эпохе 6400 = 0.46043914556503296

Потери на train на эпохе 6600 = 0.27594584226608276
Потери на test на эпохе 6600 = 0.44430527091026306

Потери на train на эпохе 6800 = 0.2349616438150406
Потери на test на эпохе 6800 = 0.4259744882583618

Потери на train на эпохе 7000 = 0.24071620404720306
Потери на test на эпохе 7000 = 0.4088699519634247

Потери на train на эпохе 7200 = 0.1946125030517578
Потери на test на эпохе 7200 = 0.39408841729164124

Потери на train на эпохе 7400 = 0.19681966304779053
Потери на test на эпохе 7400 = 0.38075685501098633

Потери на train на эпохе 7600 = 0.17832599580287933
Потери на test на эпохе 7600 = 0.36819371581077576

Потери на train на эпохе 7800 = 0.15256091952323914
Потери на test на эпохе 7800 = 0.3569946587085724

Потери на train на эпохе 8000 = 0.17051959037780762
Потери на test на эпохе 8000 = 0.3467102348804474

Потери на train на эпохе 8200 = 0.19060488045215607
Потери на test на эпохе 8200 = 0.33737197518348694

Потери на train на эпохе 8400 = 0.12249302119016647
Потери на test на эпохе 8400 = 0.3267494738101959

Потери на train на эпохе 8600 = 0.09298764169216156
Потери на test на эпохе 8600 = 0.3181958794593811

Потери на train на эпохе 8800 = 0.12183888256549835
Потери на test на эпохе 8800 = 0.3083265721797943

Потери на train на эпохе 9000 = 0.11621487140655518
Потери на test на эпохе 9000 = 0.3001915514469147

Потери на train на эпохе 9200 = 0.10360319167375565
Потери на test на эпохе 9200 = 0.29383525252342224

Потери на train на эпохе 9400 = 0.10525857657194138
Потери на test на эпохе 9400 = 0.2874174416065216

Потери на train на эпохе 9600 = 0.07977218925952911
Потери на test на эпохе 9600 = 0.2776496708393097

Потери на train на эпохе 9800 = 0.10825406759977341
Потери на test на эпохе 9800 = 0.2711774706840515

Потери на train на эпохе 10000 = 0.08592291176319122
Потери на test на эпохе 10000 = 0.26173415780067444

Потери на train на эпохе 10200 = 0.08191898465156555
Потери на test на эпохе 10200 = 0.2529012858867645

Потери на train на эпохе 10400 = 0.09301821887493134
Потери на test на эпохе 10400 = 0.24481770396232605

Потери на train на эпохе 10600 = 0.08381164819002151
Потери на test на эпохе 10600 = 0.23476722836494446

Потери на train на эпохе 10800 = 0.07102923095226288
Потери на test на эпохе 10800 = 0.2260938584804535

Потери на train на эпохе 11000 = 0.09373244643211365
Потери на test на эпохе 11000 = 0.21752682328224182

Потери на train на эпохе 11200 = 0.08747515827417374
Потери на test на эпохе 11200 = 0.21037505567073822

Потери на train на эпохе 11400 = 0.07870255410671234
Потери на test на эпохе 11400 = 0.20220492780208588

Потери на train на эпохе 11600 = 0.07588410377502441
Потери на test на эпохе 11600 = 0.19511261582374573

Потери на train на эпохе 11800 = 0.0764811560511589
Потери на test на эпохе 11800 = 0.1884673833847046

Потери на train на эпохе 12000 = 0.06399168074131012
Потери на test на эпохе 12000 = 0.18120968341827393

Потери на train на эпохе 12200 = 0.05521966144442558
Потери на test на эпохе 12200 = 0.17446580529212952

Потери на train на эпохе 12400 = 0.06541965156793594
Потери на test на эпохе 12400 = 0.16909155249595642

Потери на train на эпохе 12600 = 0.06699573248624802
Потери на test на эпохе 12600 = 0.16391564905643463

Потери на train на эпохе 12800 = 0.0591503344476223
Потери на test на эпохе 12800 = 0.15768055617809296

Потери на train на эпохе 13000 = 0.06350086629390717
Потери на test на эпохе 13000 = 0.15117581188678741

Потери на train на эпохе 13200 = 0.060500167310237885
Потери на test на эпохе 13200 = 0.14693185687065125

Потери на train на эпохе 13400 = 0.051812149584293365
Потери на test на эпохе 13400 = 0.1423475742340088

Потери на train на эпохе 13600 = 0.04391340911388397
Потери на test на эпохе 13600 = 0.13801561295986176

Потери на train на эпохе 13800 = 0.06225817650556564
Потери на test на эпохе 13800 = 0.13328905403614044

Потери на train на эпохе 14000 = 0.06466873735189438
Потери на test на эпохе 14000 = 0.1292525827884674

Потери на train на эпохе 14200 = 0.05217071622610092
Потери на test на эпохе 14200 = 0.1253594011068344

Потери на train на эпохе 14400 = 0.07026262581348419
Потери на test на эпохе 14400 = 0.12175977975130081

Потери на train на эпохе 14600 = 0.04962063953280449
Потери на test на эпохе 14600 = 0.11794861406087875

Потери на train на эпохе 14800 = 0.03942205384373665
Потери на test на эпохе 14800 = 0.11516249179840088

Потери на train на эпохе 15000 = 0.05468952655792236
Потери на test на эпохе 15000 = 0.11167936772108078

Потери на train на эпохе 15200 = 0.03980961814522743
Потери на test на эпохе 15200 = 0.10952180624008179

Потери на train на эпохе 15400 = 0.05241980776190758
Потери на test на эпохе 15400 = 0.10646490007638931

Потери на train на эпохе 15600 = 0.04137330502271652
Потери на test на эпохе 15600 = 0.10414405912160873

Потери на train на эпохе 15800 = 0.03979094326496124
Потери на test на эпохе 15800 = 0.10172313451766968

Потери на train на эпохе 16000 = 0.04092330485582352
Потери на test на эпохе 16000 = 0.09961419552564621

Потери на train на эпохе 16200 = 0.04171738773584366
Потери на test на эпохе 16200 = 0.09768219292163849

Потери на train на эпохе 16400 = 0.037327639758586884
Потери на test на эпохе 16400 = 0.09696202725172043

Потери на train на эпохе 16600 = 0.04406117647886276
Потери на test на эпохе 16600 = 0.09481839090585709

Потери на train на эпохе 16800 = 0.05235464870929718
Потери на test на эпохе 16800 = 0.09362102299928665

Потери на train на эпохе 17000 = 0.0447126105427742
Потери на test на эпохе 17000 = 0.09228350967168808

Потери на train на эпохе 17200 = 0.04156084358692169
Потери на test на эпохе 17200 = 0.09113924950361252

Потери на train на эпохе 17400 = 0.03633735328912735
Потери на test на эпохе 17400 = 0.09131481498479843

Потери на train на эпохе 17600 = 0.04767034947872162
Потери на test на эпохе 17600 = 0.08939634263515472

Потери на train на эпохе 17800 = 0.03571503981947899
Потери на test на эпохе 17800 = 0.08844172954559326

Потери на train на эпохе 18000 = 0.0348607562482357
Потери на test на эпохе 18000 = 0.08747972548007965

Потери на train на эпохе 18200 = 0.042625926434993744
Потери на test на эпохе 18200 = 0.08664164692163467

Потери на train на эпохе 18400 = 0.04044117033481598
Потери на test на эпохе 18400 = 0.08609579503536224

Потери на train на эпохе 18600 = 0.031152861192822456
Потери на test на эпохе 18600 = 0.08519317954778671

Потери на train на эпохе 18800 = 0.03752452880144119
Потери на test на эпохе 18800 = 0.08436307311058044

Потери на train на эпохе 19000 = 0.027451811358332634
Потери на test на эпохе 19000 = 0.0834992378950119

Потери на train на эпохе 19200 = 0.029627298936247826
Потери на test на эпохе 19200 = 0.08262068033218384

Потери на train на эпохе 19400 = 0.033077482134103775
Потери на test на эпохе 19400 = 0.08257510513067245

Потери на train на эпохе 19600 = 0.03500159829854965
Потери на test на эпохе 19600 = 0.08225653320550919

Потери на train на эпохе 19800 = 0.031917110085487366
Потери на test на эпохе 19800 = 0.08218204975128174

Потери на train на эпохе 20000 = 0.03486637398600578
Потери на test на эпохе 20000 = 0.08196176588535309

Потери на train на эпохе 20200 = 0.03854432329535484
Потери на test на эпохе 20200 = 0.08128219842910767

Потери на train на эпохе 20400 = 0.03000185824930668
Потери на test на эпохе 20400 = 0.08093353360891342

Потери на train на эпохе 20600 = 0.03079269826412201
Потери на test на эпохе 20600 = 0.08106710761785507

Потери на train на эпохе 20800 = 0.02992931194603443
Потери на test на эпохе 20800 = 0.08094087243080139

Потери на train на эпохе 21000 = 0.029879841953516006
Потери на test на эпохе 21000 = 0.08021453768014908

Потери на train на эпохе 21200 = 0.03677770122885704
Потери на test на эпохе 21200 = 0.0805366262793541

Потери на train на эпохе 21400 = 0.03708389028906822
Потери на test на эпохе 21400 = 0.08057884126901627

Потери на train на эпохе 21600 = 0.034797605127096176
Потери на test на эпохе 21600 = 0.08030100166797638

Потери на train на эпохе 21800 = 0.03532450646162033
Потери на test на эпохе 21800 = 0.08018902689218521

Потери на train на эпохе 22000 = 0.02950984612107277
Потери на test на эпохе 22000 = 0.08002641052007675

Потери на train на эпохе 22200 = 0.02333066426217556
Потери на test на эпохе 22200 = 0.07999356091022491

Потери на train на эпохе 22400 = 0.03426358476281166
Потери на test на эпохе 22400 = 0.07986930757761002

Потери на train на эпохе 22600 = 0.027845265343785286
Потери на test на эпохе 22600 = 0.07967830449342728

Потери на train на эпохе 22800 = 0.03458135202527046
Потери на test на эпохе 22800 = 0.07964669167995453

Потери на train на эпохе 23000 = 0.02150726690888405
Потери на test на эпохе 23000 = 0.07949908077716827

Потери на train на эпохе 23200 = 0.02827753685414791
Потери на test на эпохе 23200 = 0.07940012216567993

Потери на train на эпохе 23400 = 0.03317587077617645
Потери на test на эпохе 23400 = 0.07996318489313126

Потери на train на эпохе 23600 = 0.025709716603159904
Потери на test на эпохе 23600 = 0.07999900728464127

Потери на train на эпохе 23800 = 0.035667937248945236
Потери на test на эпохе 23800 = 0.08009108901023865

Потери на train на эпохе 24000 = 0.01987638883292675
Потери на test на эпохе 24000 = 0.08038046211004257

Потери на train на эпохе 24200 = 0.025123530998826027
Потери на test на эпохе 24200 = 0.08044413477182388

Потери на train на эпохе 24400 = 0.028012456372380257
Потери на test на эпохе 24400 = 0.08052142709493637

Потери на train на эпохе 24600 = 0.024439945816993713
Потери на test на эпохе 24600 = 0.08129289001226425

Потери на train на эпохе 24800 = 0.030341435223817825
Потери на test на эпохе 24800 = 0.08110760152339935

Потери на train на эпохе 25000 = 0.025055186823010445
Потери на test на эпохе 25000 = 0.0808778926730156

Потери на train на эпохе 25200 = 0.02843727357685566
Потери на test на эпохе 25200 = 0.08093753457069397

Модель перестала учиться, this is the end...
Лучшая эпоха: 23147 (потери на test: 0.07928977906703949)

(array([0.6, 0.8, 0.6, 0.8, 0.6, 0.4, 0.8, 0.8, 1. , 0.4, 0.8, 0.4, 0.6,
        0.4, 1. , 0.4, 0.8, 0.8, 0.8, 0.8, 0.2, 1. , 0.8, 1. , 0.2, 0.8,
        0.6, 0.8, 1. , 0.8, 0.6, 0.6, 0.6, 0.4, 0.4], dtype=float32),
 array([0.6916385 , 0.65911657, 0.83671767, 0.5566469 , 0.9412691 ,
        1.197446  , 0.86373234, 0.5266617 , 0.61686295, 0.78639406,
        0.6847644 , 0.6275471 , 0.6648397 , 0.4245677 , 0.76521856,
        0.87554246, 1.0649438 , 0.6735658 , 0.5109702 , 0.5961107 ,
        0.7627705 , 0.65486634, 0.59362674, 1.146484  , 0.35098028,
        0.9649338 , 0.59697205, 0.77334946, 0.6507928 , 0.9885053 ,
        0.98748744, 0.7095967 , 0.49604028, 0.626486  , 0.49815267],
       dtype=float32),
 0.07928977906703949)

Пожалуй, стоит провести более осмысленное сравнение двух датасетов...

Для этого **выполним 10 k-разбиений датасета и сравним средние и разброс**:

In [28]:
kf = KFold(n_splits=10, shuffle=True, random_state=RANDOM_SEED)

res1 = []
res2 = []

for train_idx, test_idx in kf.split(dataset_input1):
    kf_input1_train, kf_input1_test = dataset_input1.iloc[train_idx], dataset_input1.iloc[test_idx]
    kf_input2_train, kf_input2_test = dataset_input2.iloc[train_idx], dataset_input2.iloc[test_idx]
    kf_output_train, kf_output_test = dataset_output.iloc[train_idx], dataset_output.iloc[test_idx]

    scaler1 = StandardScaler()
    kf_input1_train = scaler1.fit_transform(kf_input1_train)
    kf_input1_test = scaler1.transform(kf_input1_test)
    scaler2 = StandardScaler()
    kf_input2_train = scaler2.fit_transform(kf_input2_train)
    kf_input2_test = scaler2.transform(kf_input2_test)

    _, _, loss = learning_pipeline(
        Dataset1Model(),
        kf_input1_train,
        kf_output_train,
        kf_input1_test,
        kf_output_test,
        comments=False
    )
    res1.append(loss)

    _, _, loss = learning_pipeline(
        Dataset2Model(),
        kf_input2_train,
        kf_output_train,
        kf_input2_test,
        kf_output_test,
        comments=False
    )
    res2.append(loss)


print(f'Первый датасет -- Avg {np.mean(res1)}, Std {np.std(res1)}')
print(f'Второй датасет -- Avg {np.mean(res2)}, Std {np.std(res2)}')

Лучшая эпоха: 5220 (потери на test: 0.12141019850969315)
Лучшая эпоха: 3211 (потери на test: 0.20064443349838257)
Лучшая эпоха: 2280 (потери на test: 0.14006905257701874)
Лучшая эпоха: 10530 (потери на test: 0.08723389357328415)
Лучшая эпоха: 5498 (потери на test: 0.035534828901290894)
Лучшая эпоха: 4355 (потери на test: 0.028525657951831818)
Лучшая эпоха: 5921 (потери на test: 0.4088318347930908)
Лучшая эпоха: 10387 (потери на test: 0.0533173494040966)
Лучшая эпоха: 9590 (потери на test: 0.048252642154693604)
Лучшая эпоха: 1934 (потери на test: 0.06513302773237228)
Лучшая эпоха: 22447 (потери на test: 0.05099791660904884)
Лучшая эпоха: 2991 (потери на test: 0.08463555574417114)
Лучшая эпоха: 19607 (потери на test: 0.07060530036687851)
Лучшая эпоха: 23334 (потери на test: 0.12964409589767456)
Лучшая эпоха: 20587 (потери на test: 0.05492726340889931)
Лучшая эпоха: 11468 (потери на test: 0.06107795238494873)
Лучшая эпоха: 19136 (потери на test: 0.0519862174987793)
Лучшая эпоха: 18952 (потери на test: 0.033904414623975754)
Лучшая эпоха: 26240 (потери на test: 0.06315777450799942)
Лучшая эпоха: 18572 (потери на test: 0.013881065882742405)
Первый датасет -- Avg 0.10457730293273926, Std 0.10631299783185054
Второй датасет -- Avg 0.075799744669348, Std 0.05230121476498564

Как видно выше, спектральные характеристики заметно точнее восстанаваливают гедонические оценки, нежели средние значения по областям мозга (однако и точность последних достаточно высока).

Но всё ещё остаётся главный вопрос...

### 5. Имеет ли смысл ансамблирование этих джвух моделей???

In [29]:
kf = KFold(n_splits=5, shuffle=True, random_state=RANDOM_SEED)


res_real = []
res_pred1 = []
res_pred2 = []

for train_idx, test_idx in kf.split(dataset_input1):
    kf_input1_train, kf_input1_test = dataset_input1.iloc[train_idx], dataset_input1.iloc[test_idx]
    kf_input2_train, kf_input2_test = dataset_input2.iloc[train_idx], dataset_input2.iloc[test_idx]
    kf_output_train, kf_output_test = dataset_output.iloc[train_idx], dataset_output.iloc[test_idx]

    scaler1 = StandardScaler()
    kf_input1_train = scaler1.fit_transform(kf_input1_train)
    kf_input1_test = scaler1.transform(kf_input1_test)
    scaler2 = StandardScaler()
    kf_input2_train = scaler2.fit_transform(kf_input2_train)
    kf_input2_test = scaler2.transform(kf_input2_test)

    real, pred1, loss1 = learning_pipeline(
        Dataset1Model(),
        kf_input1_train,
        kf_output_train,
        kf_input1_test,
        kf_output_test,
        comments=False
    )

    _, pred2, loss2 = learning_pipeline(
        Dataset2Model(),
        kf_input2_train,
        kf_output_train,
        kf_input2_test,
        kf_output_test,
        comments=False
    )

    res_pred1.append(pred1)
    res_pred2.append(pred2)
    res_real.append(real)


y = np.concatenate(res_real)
p1 = np.concatenate(res_pred1)
p2 = np.concatenate(res_pred2)

Лучшая эпоха: 7005 (потери на test: 0.21581807732582092)
Лучшая эпоха: 11079 (потери на test: 0.07467319816350937)
Лучшая эпоха: 3015 (потери на test: 0.10074514150619507)
Лучшая эпоха: 6781 (потери на test: 0.07333756238222122)
Лучшая эпоха: 17980 (потери на test: 0.06929344683885574)
Лучшая эпоха: 3808 (потери на test: 0.06358863413333893)
Лучшая эпоха: 20688 (потери на test: 0.07703740894794464)
Лучшая эпоха: 15603 (потери на test: 0.1670844405889511)
Лучшая эпоха: 5992 (потери на test: 0.04222552478313446)
Лучшая эпоха: 4371 (потери на test: 0.04296155273914337)

In [30]:
np.corrcoef(y - p1, y - p2)

array([[1.       , 0.6221718],
       [0.6221718, 1.       ]])

In [31]:
mse_1 = np.mean((y - p1) ** 2)
mse_2 = np.mean((y - p2) ** 2)
mse_1and2 = np.mean((y - (p1 + p2) / 2) ** 2)

print(mse_1, mse_2, mse_1and2)

0.101539694 0.08469196 0.07543546

### **Вывод:** хотя признаки, извлечённые sLORETA, и проигрывают спектральным характеристикам, применение двух моделей в виде ансамбля даёт существенный прирост точности.